version: '3.8'

services:
  web:
    build: .
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: ./service
        target: /service
    depends_on:
      - db

  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3307:3306'
    volumes:
      - type: bind
        source: ./db_data
        target: /var/lib/mysql
